CREATE VIEW vista_bandejaentradamensajescashmanha  AS SELECT mensajeria.idmensajeria AS idmensajeria, mensajeria.idusuarios AS idusuarios, mensajeria.idusuariosdestinatario AS idusuariosdestinatario, usuarios.nombres AS nombres, usuarios.apellidos AS apellidos, usuarios.codigousuario AS codigousuario, usuarios.fotoperfil AS fotoperfil, mensajeria.nombremensaje AS nombremensaje, mensajeria.asuntomensaje AS asuntomensaje, mensajeria.detallemensaje AS detallemensaje, mensajeria.fechamensaje AS fechamensaje, mensajeria.ocultarmensaje AS ocultarmensaje FROM (mensajeria left join usuarios on(mensajeria.idusuarios = usuarios.idusuarios));


CREATE VIEW vista_calculaduracioncodigoseguridad_transferencias  AS SELECT codigostransferencias.idcodigo AS idcodigo, codigostransferencias.codigoseguridad AS codigoseguridad, concat(timestampdiff(MINUTE,codigostransferencias.fecha,current_timestamp())) AS minutos_expiracion, codigostransferencias.estado AS estado, codigostransferencias.idusuarios AS idusuarios FROM codigostransferencias ;


CREATE VIEW vista_calculocuentasahorooregistradas_interfaces  AS SELECT count(0) AS numero_cuentasahorro_registradas FROM cuentas  ;


CREATE VIEW vista_calculocuotasregistradas_interfaces  AS SELECT count(0) AS numero_cuotas_registrados FROM cuotas ;


CREATE VIEW vista_calculocuotasvencidas_interfaces  AS SELECT count(0) AS numero_cuotas_vencidas FROM cuotas WHERE cuotas.incumplimiento_pago = 'SI''SI'  ;


CREATE VIEW vista_calculodiasfechavencimiento_cuotasclientes  AS SELECT cuotas.idcuotas AS idcuotas, cuotas.idusuarios AS idusuarios, cuotas.idproducto AS idproducto, cuotas.montocancelar AS montocancelar, cuotas.estadocuota AS estadocuota, cuotas.fechavencimiento AS fechavencimiento, cuotas.incumplimiento_pago AS incumplimiento_pago, to_days(current_timestamp()) - to_days(cuotas.fechavencimiento) AS dias_incumplimiento FROM cuotas  ;


CREATE VIEW vista_calculoexpiracion_codigocambiocredencialesusuarios  AS SELECT recuperacion.idrecuperaciones AS idrecuperaciones, recuperacion.correo AS correo, recuperacion.token AS token, recuperacion.codigo AS codigo, concat(timestampdiff(MINUTE,recuperacion.fecha,current_timestamp())) AS minutos_expiracion, recuperacion.estado AS estado FROM recuperacion  ;


CREATE VIEW vista_calculoingresostransacciones_empleadosatencionclientes  AS SELECT transacciones.empleado_gestion AS empleado_gestion, sum(transacciones.monto) AS monto_transacciones_empleados FROM transacciones GROUP BY transacciones.empleado_gestion  ;


CREATE VIEW vista_calculonumerocuotascanceladas_interfaces  AS SELECT count(0) AS numero_cuotas_canceladas FROM cuotas WHERE cuotas.estadocuota = 'cancelado''cancelado'  ;


CREATE VIEW vista_calculonumerocuotaspagadastarde_interfaces  AS SELECT count(0) AS numero_cuotas_pagadas_tarde FROM cuotas WHERE cuotas.incumplimiento_pago = 'PT''PT'  ;



CREATE VIEW vista_calculonumerotransferencias_interfaces  AS SELECT count(0) AS numero_transferencias FROM transferencias  ;


CREATE VIEW vista_calculoproductosregistrados_interfaces  AS SELECT count(0) AS numero_productos_registrados FROM productos  ;


CREATE VIEW vista_calculotransaccionescreditos_interfaces  AS SELECT count(0) AS numero_transacciones_creditos FROM transacciones  ;


CREATE VIEW vista_calculo_ultimaactividad_ticketsreportesplataforma  AS SELECT reporteproblemasplataforma.idreporte AS idreporte, reporteproblemasplataforma.idusuarios AS idusuarios, usuarios.codigousuario AS codigousuario, reporteproblemasplataforma.estado AS estado, to_days(current_timestamp()) - to_days(reporteproblemasplataforma.fechaactualizacionreporte) AS dias_ultima_actividad FROM (reporteproblemasplataforma join usuarios on(reporteproblemasplataforma.idusuarios = usuarios.idusuarios))  ;


CREATE VIEW vista_codigosseguridadtransferenciasclientes  AS SELECT codigostransferencias.idcodigo AS idcodigo, codigostransferencias.codigoseguridad AS codigoseguridad, codigostransferencias.fecha AS fecha, codigostransferencias.estado AS estado, codigostransferencias.idusuarios AS idusuarios FROM codigostransferencias  ;


CREATE VIEW vista_configuracionusuariosgeneral  AS SELECT usuarios.idusuarios AS idusuarios, usuarios.nombres AS nombres, usuarios.apellidos AS apellidos, usuarios.codigousuario AS codigousuario, usuarios.correo AS correo, usuarios.fotoperfil AS fotoperfil, usuarios.estado_usuario AS estado_usuario FROM usuarios  ;

CREATE VIEW vista_consultacalculocuotascanceladas_creditosclientes  AS SELECT cuotas.idcreditos AS idcreditos, cuotas.idusuarios AS idusuarios, cuotas.idproducto AS idproducto, cuotas.montocapital AS montocapital, count(0) AS cuotas_canceladas FROM cuotas WHERE cuotas.estadocuota = 'cancelado' GROUP BY cuotas.idusuarios ;

CREATE VIEW vista_consultacalculoavancecreditos_interfazclientes  AS SELECT creditos.idcreditos AS idcreditos, creditos.idusuarios AS idusuarios, creditos.idproducto AS idproducto, productos.nombreproducto AS nombreproducto, productos.codigo AS codigo, creditos.interescredito AS interescredito, creditos.cuotamensual AS cuotamensual, creditos.montocredito AS montocredito, creditos.plazocredito AS plazocredito, creditos.enviaralhistorico AS enviaralhistorico, vista_consultacalculocuotascanceladas_creditosclientes.cuotas_canceladas AS cuotas_canceladas, vista_consultacalculocuotascanceladas_creditosclientes.montocapital AS montocapital FROM ((creditos join productos on(creditos.idproducto = productos.idproducto)) join vista_consultacalculocuotascanceladas_creditosclientes on(vista_consultacalculocuotascanceladas_creditosclientes.idusuarios = creditos.idusuarios))  ;



CREATE VIEW vista_consultaclientesmorosos  AS SELECT vista_calculodiasfechavencimiento_cuotasclientes.idcuotas AS idcuotas, usuarios.idusuarios AS idusuarios, usuarios.nombres AS nombres, usuarios.apellidos AS apellidos, detalleusuarios.dui AS dui, productos.nombreproducto AS nombreproducto, vista_calculodiasfechavencimiento_cuotasclientes.montocancelar AS montocancelar, vista_calculodiasfechavencimiento_cuotasclientes.estadocuota AS estadocuota, vista_calculodiasfechavencimiento_cuotasclientes.fechavencimiento AS fechavencimiento, vista_calculodiasfechavencimiento_cuotasclientes.incumplimiento_pago AS incumplimiento_pago, vista_calculodiasfechavencimiento_cuotasclientes.dias_incumplimiento AS dias_incumplimiento FROM (((vista_calculodiasfechavencimiento_cuotasclientes join usuarios on(vista_calculodiasfechavencimiento_cuotasclientes.idusuarios = usuarios.idusuarios)) join productos on(vista_calculodiasfechavencimiento_cuotasclientes.idproducto = productos.idproducto)) join detalleusuarios on(usuarios.idusuarios = detalleusuarios.idusuarios))  ;


CREATE VIEW vista_consultaclientes_creditoscancelados  AS SELECT historicocreditos.idhistorico AS idhistorico, historicocreditos.idusuarios AS idusuarios, historicocreditos.idproducto AS idproducto, historicocreditos.idcreditos AS idcreditos, usuarios.nombres AS nombres, usuarios.apellidos AS apellidos, detalleusuarios.dui AS dui, detalleusuarios.nit AS nit, usuarios.fotoperfil AS fotoperfil, productos.codigo AS codigo, productos.nombreproducto AS nombreproducto, historicocreditos.montocredito AS montocredito, historicocreditos.interescredito AS interescredito, historicocreditos.plazocredito AS plazocredito, historicocreditos.cuotamensual AS cuotamensual, historicocreditos.estado AS estado FROM (((historicocreditos join usuarios on(historicocreditos.idusuarios = usuarios.idusuarios)) join productos on(productos.idproducto = historicocreditos.idproducto)) join detalleusuarios on(detalleusuarios.idusuarios = historicocreditos.idusuarios))  ;


CREATE VIEW vista_consultacompletanuevassolicitudescreditosclientesgestiones  AS SELECT usuarios.idusuarios AS idusuarios, creditos.idcreditos AS idcreditos, creditos.idproducto AS idproducto, creditos.tipocliente AS tipocliente, creditos.montocredito AS montocredito, creditos.interescredito AS interescredito, creditos.plazocredito AS plazocredito, creditos.cuotamensual AS cuotamensual, creditos.saldocredito AS saldocredito, creditos.fechasolicitud AS fechasolicitud, creditos.salariocliente AS salariocliente, creditos.progreso_solicitud AS progreso_solicitud, creditos.estado AS estado, creditos.observaciones AS observaciones, creditos.observacion_gerencia AS observacion_gerencia, creditos.observacion_presidencia AS observacion_presidencia, creditos.usuario_empleado AS usuario_empleado, creditos.cuotas_generadas AS cuotas_generadas, creditos.estadocrediticio AS estadocrediticio, creditos.proceso_finalizado AS proceso_finalizado, creditos.enviaralhistorico AS enviaralhistorico, creditos.creditoactivo AS creditoactivo, productos.codigo AS codigo, productos.nombreproducto AS nombreproducto, usuarios.nombres AS nombres, usuarios.apellidos AS apellidos, usuarios.codigousuario AS codigousuario, usuarios.fotoperfil AS fotoperfil, usuarios.idrol AS idrol, detalleusuarios.dui AS dui, detalleusuarios.nit AS nit, detalleusuarios.telefono AS telefono, detalleusuarios.celular AS celular, detalleusuarios.telefonotrabajo AS telefonotrabajo, detalleusuarios.direccion AS direccion, detalleusuarios.empresa AS empresa, detalleusuarios.cargo AS cargo, detalleusuarios.direcciontrabajo AS direcciontrabajo, detalleusuarios.fechanacimiento AS fechanacimiento, referenciaspersonales.nombres_referencia1 AS nombres_referencia1, referenciaspersonales.apellidos_referencia1 AS apellidos_referencia1, referenciaspersonales.empresa_referencia1 AS empresa_referencia1, referenciaspersonales.profesion_oficioreferencia1 AS profesion_oficioreferencia1, referenciaspersonales.telefono_referencia1 AS telefono_referencia1, referenciaspersonales.nombres_referencia2 AS nombres_referencia2, referenciaspersonales.apellidos_referencia2 AS apellidos_referencia2, referenciaspersonales.empresa_referencia2 AS empresa_referencia2, referenciaspersonales.profesion_oficioreferencia2 AS profesion_oficioreferencia2, referenciaspersonales.telefono_referencia2 AS telefono_referencia2 FROM ((((creditos join usuarios on(creditos.idusuarios = usuarios.idusuarios)) join detalleusuarios on(detalleusuarios.idusuarios = usuarios.idusuarios)) join referenciaspersonales on(referenciaspersonales.idusuarios = usuarios.idusuarios)) join productos on(productos.idproducto = creditos.idproducto))  ;


CREATE VIEW vista_consultacompletausuariosdetalles  AS SELECT usuarios.idusuarios AS idusuarios, usuarios.nombres AS nombres, usuarios.apellidos AS apellidos, usuarios.codigousuario AS codigousuario, usuarios.correo AS correo, usuarios.fotoperfil AS fotoperfil, usuarios.idrol AS idrol, usuarios.estado_usuario AS estado_usuario, usuarios.completoperfil AS completoperfil, usuarios.quienregistro AS quienregistro, detalleusuarios.dui AS dui, detalleusuarios.nit AS nit, detalleusuarios.telefono AS telefono, detalleusuarios.celular AS celular, detalleusuarios.telefonotrabajo AS telefonotrabajo, detalleusuarios.direccion AS direccion, detalleusuarios.empresa AS empresa, detalleusuarios.cargo AS cargo, detalleusuarios.direcciontrabajo AS direcciontrabajo, detalleusuarios.fechanacimiento AS fechanacimiento, detalleusuarios.genero AS genero, detalleusuarios.estadocivil AS estadocivil, detalleusuarios.fotoduifrontal AS fotoduifrontal, detalleusuarios.fotoduireverso AS fotoduireverso, detalleusuarios.fotonit AS fotonit, detalleusuarios.fotofirma AS fotofirma FROM (usuarios left join detalleusuarios on(detalleusuarios.idusuarios = usuarios.idusuarios))  ;


CREATE VIEW vista_consultacopiascontrato_suscritocreditosclientes  AS SELECT usuarios.idusuarios AS idusuarios, creditos.copiacontratocliente AS copiacontratocliente, usuarios.nombres AS nombres, usuarios.apellidos AS apellidos, usuarios.codigousuario AS codigousuario FROM (creditos join usuarios on(creditos.idusuarios = usuarios.idusuarios))  ;

CREATE VIEW vista_consultacuotasgeneradas_creditosaprobadosclientes  AS SELECT cuotas.idcuotas AS idcuotas, usuarios.idusuarios AS idusuarios, productos.idproducto AS idproducto, creditos.idcreditos AS idcreditos, usuarios.nombres AS nombres, usuarios.apellidos AS apellidos, usuarios.fotoperfil AS fotoperfil, detalleusuarios.dui AS dui, detalleusuarios.nit AS nit, creditos.montocredito AS montocredito, creditos.interescredito AS interescredito, creditos.plazocredito AS plazocredito, creditos.cuotamensual AS cuotamensual, cuotas.montocancelar AS montocancelar, cuotas.estadocuota AS estadocuota, cuotas.nombreproducto AS nombreproducto, cuotas.montocapital AS montocapital, cuotas.fechavencimiento AS fechavencimiento, cuotas.incumplimiento_pago AS incumplimiento_pago, to_days(current_timestamp()) - to_days(cuotas.fechavencimiento) AS dias_incumplimiento FROM ((((cuotas join usuarios on(cuotas.idusuarios = usuarios.idusuarios)) join productos on(productos.idproducto = cuotas.idproducto)) join detalleusuarios on(detalleusuarios.idusuarios = usuarios.idusuarios)) join creditos on(creditos.idusuarios = usuarios.idusuarios))  ;


CREATE VIEW vista_consultacuotashistoricocreditosclientes  AS SELECT historicotransacciones.idhistoricotransaccion, historicotransacciones.idusuarios, historicotransacciones.idproducto, historicotransacciones.idcreditos, historicotransacciones.idcuotas, historicocreditos.montocredito, historicocreditos.interescredito, historicocreditos.plazocredito, historicocreditos.cuotamensual, historicotransacciones.monto, historicotransacciones.referencia, historicotransacciones.monto, historicotransacciones.fecha, historicotransacciones.dias_incumplimiento, historicotransacciones.empleado_gestion FROM historicotransacciones INNER JOIN historicocreditos ON historicotransacciones.idcreditos = historicocreditos.idcreditos;

CREATE VIEW vista_consultadatosprestamosdevehiculosclientes  AS SELECT datosvehiculoscreditos.iddatosvehiculos AS iddatosvehiculos, datosvehiculoscreditos.idcreditos AS idcreditos, datosvehiculoscreditos.idproducto AS idproducto, datosvehiculoscreditos.idusuarios AS idusuarios, datosvehiculoscreditos.placa AS placa, datosvehiculoscreditos.clase AS clase, datosvehiculoscreditos.anio AS anio, datosvehiculoscreditos.capacidad AS capacidad, datosvehiculoscreditos.asientos AS asientos, datosvehiculoscreditos.marca AS marca, datosvehiculoscreditos.modelo AS modelo, datosvehiculoscreditos.numeromotor AS numeromotor, datosvehiculoscreditos.chasisgrabado AS chasisgrabado, datosvehiculoscreditos.chasisvin AS chasisvin, datosvehiculoscreditos.color AS color FROM datosvehiculoscreditos  ;

CREATE VIEW vista_consultadetallecompletotransaccionescuentasclientes  AS SELECT transaccionescuentasclientes.idtransaccioncuentas AS idtransaccioncuentas, transaccionescuentasclientes.idusuarios AS idusuarios, transaccionescuentasclientes.idproducto AS idproducto, transaccionescuentasclientes.idcuentas AS idcuentas, usuarios.nombres AS nombres, usuarios.apellidos AS apellidos, productos.codigo AS codigo, productos.nombreproducto AS nombreproducto, cuentas.numerocuenta AS numerocuenta, transaccionescuentasclientes.referencia AS referencia, transaccionescuentasclientes.monto AS monto, transaccionescuentasclientes.fecha AS fecha, transaccionescuentasclientes.empleado_gestion AS empleado_gestion, transaccionescuentasclientes.tipotransaccion AS tipotransaccion, transaccionescuentasclientes.estadotransaccion AS estadotransaccion FROM (((transaccionescuentasclientes join usuarios on(transaccionescuentasclientes.idusuarios = usuarios.idusuarios)) join productos on(transaccionescuentasclientes.idproducto = productos.idproducto)) join cuentas on(transaccionescuentasclientes.idcuentas = cuentas.idcuentas))  ;

CREATE VIEW vista_consultadetallesinterfazpresidencia  AS SELECT vista_calculoproductosregistrados_interfaces.numero_productos_registrados AS numero_productos_registrados, vista_calculocuotasregistradas_interfaces.numero_cuotas_registrados AS numero_cuotas_registrados, vista_calculocuentasahorooregistradas_interfaces.numero_cuentasahorro_registradas AS numero_cuentasahorro_registradas, vista_calculotransaccionescreditos_interfaces.numero_transacciones_creditos AS numero_transacciones_creditos FROM (((vista_calculoproductosregistrados_interfaces left join vista_calculocuotasregistradas_interfaces on(vista_calculoproductosregistrados_interfaces.numero_productos_registrados = vista_calculoproductosregistrados_interfaces.numero_productos_registrados)) left join vista_calculocuentasahorooregistradas_interfaces on(vista_calculoproductosregistrados_interfaces.numero_productos_registrados = vista_calculoproductosregistrados_interfaces.numero_productos_registrados)) left join vista_calculotransaccionescreditos_interfaces on(vista_calculoproductosregistrados_interfaces.numero_productos_registrados = vista_calculoproductosregistrados_interfaces.numero_productos_registrados))  ;


CREATE VIEW vista_consultadetallessolicitudescreditosaprobadosclientes  AS SELECT usuarios.idusuarios AS idusuarios, creditos.idcreditos AS idcreditos, creditos.idproducto AS idproducto, creditos.montocredito AS montocredito, creditos.interescredito AS interescredito, creditos.plazocredito AS plazocredito, creditos.cuotamensual AS cuotamensual, creditos.fechasolicitud AS fechasolicitud, creditos.estado AS estado, usuarios.nombres AS nombres, usuarios.apellidos AS apellidos, usuarios.codigousuario AS codigousuario, usuarios.correo AS correo, usuarios.fotoperfil AS fotoperfil, detalleusuarios.dui AS dui, detalleusuarios.nit AS nit FROM ((creditos join usuarios on(creditos.idusuarios = usuarios.idusuarios)) join detalleusuarios on(detalleusuarios.idusuarios = usuarios.idusuarios))  ;


CREATE VIEW vista_consultaestadosolicitudcredito_portalclientesbienvenida  AS SELECT creditos.idusuarios AS idusuarios, creditos.estado AS estado, creditos.progreso_solicitud AS progreso_solicitud, productos.nombreproducto AS nombreproducto, productos.codigo AS codigo FROM ((creditos join usuarios on(creditos.idusuarios = usuarios.idusuarios)) join productos on(creditos.idproducto = productos.idproducto))  ;


CREATE VIEW vista_consultaexistenciacuotasmensualesclientes  AS SELECT cuotas.idcuotas AS idcuotas, cuotas.idcreditos AS idcreditos, cuotas.idproducto AS idproducto, cuotas.idusuarios AS idusuarios, cuotas.nombreproducto AS nombreproducto FROM cuotas  ;


CREATE VIEW vista_consultaexistenciareferenciasclientes  AS SELECT referenciaspersonales.idreferencias AS idreferencias, referenciaspersonales.idcreditos AS idcreditos, usuarios.idusuarios AS idusuarios, referenciaspersonales.idproducto AS idproducto, referenciaspersonales.nombres_referencia1 AS nombres_referencia1, referenciaspersonales.apellidos_referencia1 AS apellidos_referencia1, referenciaspersonales.empresa_referencia1 AS empresa_referencia1, referenciaspersonales.profesion_oficioreferencia1 AS profesion_oficioreferencia1, referenciaspersonales.telefono_referencia1 AS telefono_referencia1, referenciaspersonales.nombres_referencia2 AS nombres_referencia2, referenciaspersonales.apellidos_referencia2 AS apellidos_referencia2, referenciaspersonales.empresa_referencia2 AS empresa_referencia2, referenciaspersonales.profesion_oficioreferencia2 AS profesion_oficioreferencia2, referenciaspersonales.telefono_referencia2 AS telefono_referencia2 FROM (referenciaspersonales join usuarios on(referenciaspersonales.idusuarios = usuarios.idusuarios))  ;


CREATE VIEW vista_consultageneralreestructuracioncreditosclientes  AS SELECT a.idusuarios AS idusuarios, a.idcreditos AS idcreditos, a.montocredito AS montocredito, a.interescredito AS interescredito, a.plazocredito AS plazocredito, a.cuotamensual AS cuotamensual, a.estado AS estado, a.fechasolicitud AS fechasolicitud, a.cuotas_generadas AS cuotas_generadas, b.nombres AS nombres, b.apellidos AS apellidos, b.codigousuario AS codigousuario, b.fotoperfil AS fotoperfil, c.dui AS dui, c.nit AS nit FROM ((creditos a join usuarios b on(a.idusuarios = b.idusuarios)) join detalleusuarios c on(a.idusuarios = c.idusuarios))  ;

CREATE VIEW vista_consultageneralusuarios  AS SELECT usuarios.idusuarios AS idusuarios, usuarios.nombres AS nombres, usuarios.apellidos AS apellidos, usuarios.codigousuario AS codigousuario, usuarios.correo AS correo, usuarios.fotoperfil AS fotoperfil, usuarios.idrol AS idrol, usuarios.estado_usuario AS estado_usuario, usuarios.completoperfil AS completoperfil FROM usuarios  ;


CREATE VIEW vista_consultalistadogeneralcuentasahorrosregistradas  AS SELECT cuentas.idcuentas AS idcuentas, cuentas.idusuarios AS idusuarios, usuarios.nombres AS nombres, usuarios.apellidos AS apellidos, usuarios.fotoperfil AS fotoperfil, detalleusuarios.dui AS dui, detalleusuarios.nit AS nit, cuentas.numerocuenta AS numerocuenta, cuentas.montocuenta AS montocuenta, cuentas.estadocuenta AS estadocuenta, cuentas.fechaapertura AS fechaapertura FROM ((cuentas join usuarios on(cuentas.idusuarios = usuarios.idusuarios)) join detalleusuarios on(cuentas.idusuarios = detalleusuarios.idusuarios))  ;

CREATE VIEW vista_consultanuevo_prestamopersonal_asignado_clientes  AS SELECT creditos.idproducto AS idproducto, creditos.idcreditos AS idcreditos, productos.codigo AS codigo, productos.nombreproducto AS nombreproducto, creditos.fechasolicitud AS fechasolicitud, creditos.montocredito AS montocredito, creditos.interescredito AS interescredito, creditos.plazocredito AS plazocredito, creditos.progreso_solicitud AS progreso_solicitud, creditos.progreso_pagocredito AS progreso_pagocredito, creditos.estado AS estado, usuarios.nombres AS nombres, usuarios.apellidos AS apellidos, usuarios.codigousuario AS codigousuario, usuarios.idusuarios AS idusuarios FROM ((creditos join usuarios on(creditos.idusuarios = usuarios.idusuarios)) join productos on(productos.idproducto = creditos.idproducto))  ;

CREATE VIEW vista_consultanumeroreportesfallasplataformageneral  AS SELECT count(reporteproblemasplataforma.idreporte) AS numero_reportes_registrados FROM reporteproblemasplataforma  ;

CREATE VIEW vista_consultanumerosolicitudesrecuperaciones  AS SELECT count(recuperacion.idrecuperaciones) AS numero_solicitudes_recuperaciones FROM recuperacion  ;

CREATE VIEW vista_consultaproductosnuevoscreditos  AS SELECT productos.idproducto AS idproducto, productos.codigo AS codigo, productos.nombreproducto AS nombreproducto, productos.estado AS estado FROM productos  ;



CREATE VIEW vista_consultaproductosregistrados  AS SELECT count(productos.idproducto) AS numero_productos_registrados FROM productos  ;


CREATE VIEW vista_consultardisponibilidadnuevoscreditosclientes  AS SELECT usuarios.idusuarios AS idusuarios, usuarios.nombres AS nombres, usuarios.apellidos AS apellidos, usuarios.codigousuario AS codigousuario, usuarios.habilitarnuevoscreditos AS habilitarnuevoscreditos FROM usuarios  ;


CREATE VIEW vista_consultareportesfallosplataforma  AS SELECT reporteproblemasplataforma.idreporte AS idreporte, reporteproblemasplataforma.idusuarios AS idusuarios, usuarios.codigousuario AS codigousuario, reporteproblemasplataforma.nombrereporte AS nombrereporte, reporteproblemasplataforma.descripcionreporte AS descripcionreporte, reporteproblemasplataforma.fotoreporte AS fotoreporte, reporteproblemasplataforma.fecharegistroreporte AS fecharegistroreporte, reporteproblemasplataforma.fechaactualizacionreporte AS fechaactualizacionreporte, reporteproblemasplataforma.estado AS estado, reporteproblemasplataforma.comentarioactualizacion AS comentarioactualizacion, reporteproblemasplataforma.empleado_gestion AS empleado_gestion FROM (reporteproblemasplataforma join usuarios on(reporteproblemasplataforma.idusuarios = usuarios.idusuarios))  ;


CREATE VIEW vista_consultatransaccionesclientesgeneral  AS SELECT cuotas.idcuotas AS idcuotas, transacciones.idusuarios AS idusuarios, transacciones.referencia AS referencia, transacciones.monto AS monto, transacciones.fecha AS fecha, transacciones.empleado_gestion AS empleado_gestion, usuarios.nombres AS nombres, usuarios.apellidos AS apellidos, usuarios.habilitarnuevoscreditos AS habilitarnuevoscreditos FROM ((transacciones join usuarios on(transacciones.idusuarios = usuarios.idusuarios)) join cuotas on(cuotas.idcuotas = transacciones.idcuotas))  ;


CREATE VIEW vista_consultatransaccionescuentasclientes  AS SELECT transaccionescuentasclientes.idtransaccioncuentas AS idtransaccioncuentas, transaccionescuentasclientes.idusuarios AS idusuarios, transaccionescuentasclientes.idproducto AS idproducto, transaccionescuentasclientes.idcuentas AS idcuentas, cuentas.numerocuenta AS numerocuenta, productos.codigo AS codigo, productos.nombreproducto AS nombreproducto, usuarios.nombres AS nombres, usuarios.apellidos AS apellidos, detalleusuarios.dui AS dui, detalleusuarios.nit AS nit, transaccionescuentasclientes.referencia AS referencia, transaccionescuentasclientes.monto AS monto, transaccionescuentasclientes.fecha AS fecha, transaccionescuentasclientes.empleado_gestion AS empleado_gestion, transaccionescuentasclientes.tipotransaccion AS tipotransaccion, transaccionescuentasclientes.estadotransaccion AS estadotransaccion, transaccionescuentasclientes.saldonuevocuenta_transaccion AS saldonuevocuenta_transaccion FROM ((((transaccionescuentasclientes join usuarios on(transaccionescuentasclientes.idusuarios = usuarios.idusuarios)) join detalleusuarios on(transaccionescuentasclientes.idusuarios = detalleusuarios.idusuarios)) join productos on(transaccionescuentasclientes.idproducto = productos.idproducto)) join cuentas on(transaccionescuentasclientes.idcuentas = cuentas.idcuentas))  ;


CREATE VIEW vista_consultausuariosnuevascuentas_ahorros_depositosplazofijo  AS SELECT usuarios.idusuarios AS idusuarios, usuarios.nombres AS nombres, usuarios.apellidos AS apellidos, detalleusuarios.dui AS dui FROM (usuarios join detalleusuarios on(usuarios.idusuarios = detalleusuarios.idusuarios))  ;


CREATE VIEW vista_consultausuariosregistrados  AS SELECT count(usuarios.idusuarios) AS numero_usuarios_registrados FROM usuarios  ;


CREATE VIEW vista_consulta_asignarnuevoscreditosclientes  AS SELECT usuarios.idusuarios AS idusuarios, usuarios.nombres AS nombres, usuarios.apellidos AS apellidos, usuarios.codigousuario AS codigousuario, usuarios.correo AS correo, usuarios.fotoperfil AS fotoperfil, usuarios.completoperfil AS completoperfil, usuarios.estado_usuario AS estado_usuario, usuarios.habilitarnuevoscreditos AS habilitarnuevoscreditos, detalleusuarios.dui AS dui, detalleusuarios.nit AS nit, detalleusuarios.telefono AS telefono, detalleusuarios.celular AS celular, detalleusuarios.telefonotrabajo AS telefonotrabajo, detalleusuarios.direccion AS direccion, detalleusuarios.empresa AS empresa, detalleusuarios.cargo AS cargo, detalleusuarios.direcciontrabajo AS direcciontrabajo, detalleusuarios.fechanacimiento AS fechanacimiento, detalleusuarios.genero AS genero, detalleusuarios.estadocivil AS estadocivil, detalleusuarios.fotoduifrontal AS fotoduifrontal, detalleusuarios.fotoduireverso AS fotoduireverso, detalleusuarios.fotonit AS fotonit, detalleusuarios.fotofirma AS fotofirma FROM (usuarios left join detalleusuarios on(usuarios.idusuarios = detalleusuarios.idusuarios))  ; 


CREATE VIEW vista_numerocuotasregistradas  AS SELECT count(cuotas.idcuotas) AS numero_cuotas FROM cuotas  ;

CREATE VIEW vista_numerotransaccionesprocesadas  AS SELECT count(transacciones.idtransaccion) AS numero_transacciones FROM transacciones  ;


CREATE VIEW vista_consulta_datosgeneralesresultadosinicioadmins  AS SELECT vista_consultausuariosregistrados.numero_usuarios_registrados AS numero_usuarios_registrados, vista_consultaproductosregistrados.numero_productos_registrados AS numero_productos_registrados, vista_consultanumeroreportesfallasplataformageneral.numero_reportes_registrados AS numero_reportes_registrados, vista_consultanumerosolicitudesrecuperaciones.numero_solicitudes_recuperaciones AS numero_solicitudes_recuperaciones, vista_numerocuotasregistradas.numero_cuotas AS numero_cuotas, vista_numerotransaccionesprocesadas.numero_transacciones AS numero_transacciones FROM (((((vista_consultausuariosregistrados left join vista_consultaproductosregistrados on(vista_consultausuariosregistrados.numero_usuarios_registrados = vista_consultausuariosregistrados.numero_usuarios_registrados)) left join vista_consultanumeroreportesfallasplataformageneral on(vista_consultausuariosregistrados.numero_usuarios_registrados = vista_consultausuariosregistrados.numero_usuarios_registrados)) left join vista_consultanumerosolicitudesrecuperaciones on(vista_consultausuariosregistrados.numero_usuarios_registrados = vista_consultausuariosregistrados.numero_usuarios_registrados)) left join vista_numerocuotasregistradas on(vista_consultausuariosregistrados.numero_usuarios_registrados = vista_consultausuariosregistrados.numero_usuarios_registrados)) left join vista_numerotransaccionesprocesadas on(vista_consultausuariosregistrados.numero_usuarios_registrados = vista_consultausuariosregistrados.numero_usuarios_registrados))  ;

CREATE VIEW vista_contadorcreditosgestionados_empleadosatencionclientes  AS SELECT creditos.usuario_empleado AS usuario_empleado, count(0) AS numero_creditos_gestionados FROM creditos GROUP BY creditos.usuario_empleado ;


CREATE VIEW vista_contadorincumplimientopagoscreditosclientes  AS SELECT usuarios.idusuarios AS idusuarios, usuarios.nombres AS nombres, usuarios.apellidos AS apellidos, count(0) AS total_incumplimientos_pagos FROM (cuotas join usuarios on(cuotas.idusuarios = usuarios.idusuarios)) WHERE cuotas.incumplimiento_pago = 'PT' GROUP BY usuarios.idusuarios  ;


CREATE VIEW vista_contadorpagosatiempo_creditosclientes  AS SELECT cuotas.idusuarios AS idusuarios, creditos.idcreditos AS idcreditos, cuotas.idcuotas AS idcuotas, usuarios.nombres AS nombres, usuarios.apellidos AS apellidos, creditos.estadocrediticio AS estadocrediticio, count(cuotas.incumplimiento_pago) AS cuotas_pagadas FROM ((cuotas join usuarios on(cuotas.idusuarios = usuarios.idusuarios)) join creditos on(creditos.idusuarios = usuarios.idusuarios)) WHERE cuotas.incumplimiento_pago = 'NO' AND cuotas.estadocuota = 'cancelado' GROUP BY cuotas.idusuarios  ;


CREATE VIEW vista_contadorpagoscuotastardias_creditosclientes  AS SELECT cuotas.idusuarios AS idusuarios, creditos.idcreditos AS idcreditos, cuotas.idcuotas AS idcuotas, usuarios.nombres AS nombres, usuarios.apellidos AS apellidos, creditos.estadocrediticio AS estadocrediticio, count(cuotas.incumplimiento_pago) AS cuotas_pagadas_tarde FROM ((cuotas join usuarios on(cuotas.idusuarios = usuarios.idusuarios)) join creditos on(creditos.idusuarios = usuarios.idusuarios)) WHERE cuotas.incumplimiento_pago = 'PT' GROUP BY cuotas.idusuarios  ;


CREATE VIEW vista_contadortransacciones_empleadosatencionclientes  AS SELECT count(0) AS numero_transacciones_empleados_atencionclientes, transacciones.empleado_gestion AS empleado_gestion FROM transacciones GROUP BY transacciones.empleado_gestion  ;


CREATE VIEW vista_datosgeneralescreditoscanceladoshistoricoclientes  AS SELECT historicocreditos.idhistorico AS idhistorico, historicocreditos.idproducto AS idproducto, historicocreditos.idusuarios AS idusuarios, historicocreditos.idcreditos AS idcreditos, historicocreditos.montocredito AS montocredito, historicocreditos.interescredito AS interescredito, historicocreditos.plazocredito AS plazocredito, historicocreditos.cuotamensual AS cuotamensual, historicocreditos.estado AS estado, usuarios.nombres AS nombres, usuarios.apellidos AS apellidos, usuarios.fotoperfil AS fotoperfil, productos.nombreproducto AS nombreproducto FROM ((historicocreditos join usuarios on(historicocreditos.idusuarios = usuarios.idusuarios)) join productos on(historicocreditos.idproducto = productos.idproducto))  ;


CREATE VIEW vista_detallecompletotransaccionesempleados  AS SELECT transacciones.idtransaccion AS idtransaccion, transacciones.idusuarios AS idusuarios, transacciones.idproducto AS idproducto, transacciones.idcreditos AS idcreditos, transacciones.idcuotas AS idcuotas, transacciones.referencia AS referencia, transacciones.monto AS monto, transacciones.fecha AS fecha, transacciones.dias_incumplimiento AS dias_incumplimiento, transacciones.empleado_gestion AS empleado_gestion FROM transacciones  ;


CREATE VIEW vista_detalleinterfazgerencia  AS SELECT vista_calculoproductosregistrados_interfaces.numero_productos_registrados AS numero_productos_registrados, vista_calculocuotasregistradas_interfaces.numero_cuotas_registrados AS numero_cuotas_registrados, vista_calculocuentasahorooregistradas_interfaces.numero_cuentasahorro_registradas AS numero_cuentasahorro_registradas, vista_calculotransaccionescreditos_interfaces.numero_transacciones_creditos AS numero_transacciones_creditos, vista_calculonumerocuotaspagadastarde_interfaces.numero_cuotas_pagadas_tarde AS numero_cuotas_pagadas_tarde, vista_calculonumerocuotascanceladas_interfaces.numero_cuotas_canceladas AS numero_cuotas_canceladas, vista_calculonumerotransferencias_interfaces.numero_transferencias AS numero_transferencias, vista_calculocuotasvencidas_interfaces.numero_cuotas_vencidas AS numero_cuotas_vencidas FROM (((((((vista_calculoproductosregistrados_interfaces left join vista_calculocuotasregistradas_interfaces on(vista_calculoproductosregistrados_interfaces.numero_productos_registrados = vista_calculoproductosregistrados_interfaces.numero_productos_registrados)) left join vista_calculocuentasahorooregistradas_interfaces on(vista_calculoproductosregistrados_interfaces.numero_productos_registrados = vista_calculoproductosregistrados_interfaces.numero_productos_registrados)) left join vista_calculotransaccionescreditos_interfaces on(vista_calculoproductosregistrados_interfaces.numero_productos_registrados = vista_calculoproductosregistrados_interfaces.numero_productos_registrados)) left join vista_calculonumerocuotaspagadastarde_interfaces on(vista_calculoproductosregistrados_interfaces.numero_productos_registrados = vista_calculoproductosregistrados_interfaces.numero_productos_registrados)) left join vista_calculonumerocuotascanceladas_interfaces on(vista_calculoproductosregistrados_interfaces.numero_productos_registrados = vista_calculoproductosregistrados_interfaces.numero_productos_registrados)) left join vista_calculonumerotransferencias_interfaces on(vista_calculoproductosregistrados_interfaces.numero_productos_registrados = vista_calculoproductosregistrados_interfaces.numero_productos_registrados)) left join vista_calculocuotasvencidas_interfaces on(vista_calculoproductosregistrados_interfaces.numero_productos_registrados = vista_calculoproductosregistrados_interfaces.numero_productos_registrados))  ;


CREATE VIEW vista_detallesfacturacioncreditosclientes  AS SELECT cuotas.idcuotas AS idcuotas, cuotas.idcreditos AS idcreditos, cuotas.idproducto AS idproducto, cuotas.idusuarios AS idusuarios, usuarios.nombres AS nombres, usuarios.apellidos AS apellidos, detalleusuarios.dui AS dui, detalleusuarios.nit AS nit, creditos.cuotamensual AS cuotamensual, cuotas.montocancelar AS montocancelar, cuotas.nombreproducto AS nombreproducto, productos.codigo AS codigo, cuotas.montocapital AS montocapital, cuotas.fechavencimiento AS fechavencimiento, transacciones.referencia AS referencia, transacciones.fecha AS fecha, transacciones.dias_incumplimiento AS dias_incumplimiento, transacciones.empleado_gestion AS empleado_gestion FROM (((((cuotas join usuarios on(cuotas.idusuarios = usuarios.idusuarios)) join detalleusuarios on(detalleusuarios.idusuarios = usuarios.idusuarios)) join transacciones on(transacciones.idcuotas = cuotas.idcuotas)) join creditos on(creditos.idusuarios = usuarios.idusuarios)) join productos on(productos.idproducto = cuotas.idproducto))  ;


CREATE VIEW vista_detallesfacturacioncreditosclienteshistoricos  AS SELECT historicocuotascreditos.idhistorico AS idhistorico, historicocuotascreditos.idcreditos AS idcreditos, historicotransacciones.idcuotas, historicocuotascreditos.idproducto AS idproducto, historicocuotascreditos.idusuarios AS idusuarios, historicocuotascreditos.montocancelar AS montocancelar, historicocuotascreditos.nombreproducto AS nombreproducto, historicocuotascreditos.montocapital AS montocapital, historicocuotascreditos.fechavencimiento AS fechavencimiento FROM historicocuotascreditos INNER JOIN historicotransacciones ON historicotransacciones.idhistoricotransaccion = historicocuotascreditos.idcreditos; ;


CREATE VIEW vista_detallesusuarios  AS SELECT detalleusuarios.iddetalle AS iddetalle, detalleusuarios.dui AS dui, detalleusuarios.nit AS nit, detalleusuarios.telefono AS telefono, detalleusuarios.celular AS celular, detalleusuarios.telefonotrabajo AS telefonotrabajo, detalleusuarios.direccion AS direccion, detalleusuarios.empresa AS empresa, detalleusuarios.cargo AS cargo, detalleusuarios.direcciontrabajo AS direcciontrabajo, detalleusuarios.fechanacimiento AS fechanacimiento, detalleusuarios.genero AS genero, detalleusuarios.estadocivil AS estadocivil, detalleusuarios.idusuarios AS idusuarios FROM detalleusuarios  ;


CREATE VIEW vista_notificacionesrecibidasusuarios  AS SELECT notificaciones.idnotificacion AS idnotificacion, notificaciones.idusuarios AS idusuarios, notificaciones.titulonotificacion AS titulonotificacion, notificaciones.descripcionnotificacion AS descripcionnotificacion, notificaciones.fechanotificacion AS fechanotificacion, notificaciones.clasificacionnotificacion AS clasificacionnotificacion, notificaciones.ocultarnotificacion AS ocultarnotificacion FROM notificaciones  ;



CREATE VIEW vista_productoscashmanha  AS SELECT productos.idproducto AS idproducto, productos.codigo AS codigo, productos.nombreproducto AS nombreproducto, productos.descripcionproducto AS descripcionproducto, productos.requisitosproductos AS requisitosproductos, productos.estado AS estado FROM productos  ;


CREATE VIEW vista_reporteiniciosdesesiones  AS SELECT accesos.idacceso AS idacceso, accesos.fechaacceso AS fechaacceso, accesos.dispositivo AS dispositivo, accesos.sistemaoperativo AS sistemaoperativo, accesos.idusuarios AS idusuarios FROM accesos  ;


CREATE VIEW vista_rolesdeusuarioscompleto  AS SELECT roles.idrol AS idrol, roles.nombrerol AS nombrerol, roles.descripcionrol AS descripcionrol FROM roles  ;


CREATE VIEW vista_transaccionespagocuotascreditosclientes  AS SELECT transacciones.idtransaccion AS idtransaccion, transacciones.idusuarios AS idusuarios, transacciones.idcuotas AS idcuotas, transacciones.referencia AS referencia, transacciones.monto AS monto, transacciones.fecha AS fecha FROM transacciones  ;


CREATE VIEW vista_usuariosperfilincompleto  AS SELECT usuarios.idusuarios AS idusuarios, usuarios.nombres AS nombres, usuarios.apellidos AS apellidos, usuarios.codigousuario AS codigousuario, usuarios.correo AS correo, usuarios.fotoperfil AS fotoperfil, usuarios.idrol AS idrol, usuarios.estado_usuario AS estado_usuario, usuarios.completoperfil AS completoperfil, usuarios.quienregistro AS quienregistro FROM usuarios  ;
